spring:
  profiles: peer3

server:
  port: 8763

eureka:
  instance:
    hostname: peer3
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/, http://peer1:8761/eureka/